FROM node:18

WORKDIR /app
COPY ./export/web ./

# Install dependancy

RUN npm init -y \
&&  npm install express showdown fs path dotenv asciidoctor downdoc cheerio \
&& npm audit fix --force 

# Expose port from .env file ($PORT)
EXPOSE $PORT

CMD  ls /clone; node server.js