services:
  processor:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: 'processor'
    volumes:
      - /home/kali/Desktop/R2TI:/data:ro
      - shared:/shared:rw

  web:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: 'web'
    environment:
      - DATA_PATH=/shared/redview
    volumes:
      - shared:/shared:rw
    depends_on:
      - processor
    expose:
      - 3000
    ports:
      - "127.0.0.1:3000:3000"

volumes:
  shared: