services:
  processor:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: 'processor'
    volumes:
      - ${VOLUME_SOURCE}:/data:ro
      - clone:/clone:rw

  web:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: 'web'
    environment:
      - DATA_PATH=/clone/redview
    volumes:
      - ${VOLUME_SOURCE}:/data:ro
      - clone:/clone:rw
    depends_on:
      - processor
    expose:
      - 3000
    ports:
      - "127.0.0.1:3000:3000"

volumes:
  clone: