FROM node:18

WORKDIR /app
COPY ./export/web ./

# Install dependancy

RUN npm init -y \
&&  npm install express showdown fs path dotenv asciidoctor downdoc \
&& npm audit fix --force 

EXPOSE 3000

CMD  ls /shared; node server.js